"""Studio presentation and PDF export features"""
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from io import BytesIO
from typing import Dict, List
from datetime import datetime

class StudioPresentationGenerator:
    """Generate professional studio presentations"""
    
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        """Setup custom styles for presentation"""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1e40af'),
            spaceAfter=30,
            alignment=TA_CENTER
        ))
        
        self.styles.add(ParagraphStyle(
            name='SubTitle',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#3b82f6'),
            spaceAfter=12
        ))
        
        self.styles.add(ParagraphStyle(
            name='Highlight',
            parent=self.styles['Normal'],
            fontSize=14,
            textColor=colors.HexColor('#10b981'),
            fontName='Helvetica-Bold'
        ))
    
    def generate_pitch_deck(self, concept: Dict, prediction: Dict) -> BytesIO:
        """Generate PDF pitch deck"""
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        story = []
        
        # Title Page
        story.append(Spacer(1, 2*inch))
        title = Paragraph("<b>Film Concept Analysis</b>", self.styles['CustomTitle'])
        story.append(title)
        story.append(Spacer(1, 0.3*inch))
        
        subtitle = Paragraph(f"Generated by CineSignal", self.styles['Normal'])
        story.append(subtitle)
        story.append(Spacer(1, 0.1*inch))
        
        date_text = Paragraph(f"Date: {datetime.now().strftime('%B %d, %Y')}", self.styles['Normal'])
        story.append(date_text)
        story.append(PageBreak())
        
        # Executive Summary
        story.append(Paragraph("<b>Executive Summary</b>", self.styles['SubTitle']))
        story.append(Spacer(1, 0.2*inch))
        
        summary_data = [
            ['Success Score:', f"{prediction['overall_score']}/100"],
            ['Prediction:', prediction['label']],
            ['Confidence Level:', prediction['confidence']],
            ['India Market Fit:', f"{prediction['market_scores']['india_fit']}%"],
            ['Global Market Fit:', f"{prediction['market_scores']['global_fit']}%"]
        ]
        
        summary_table = Table(summary_data, colWidths=[3*inch, 3*inch])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#f1f5f9')),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#cbd5e1'))
        ]))
        story.append(summary_table)
        story.append(Spacer(1, 0.5*inch))
        
        # Concept Details
        story.append(Paragraph("<b>Concept Details</b>", self.styles['SubTitle']))
        story.append(Spacer(1, 0.2*inch))
        
        concept_text = f"""
        <b>Genres:</b> {', '.join(concept['genres'])}<br/>
        <b>Tone:</b> {concept['tone']}<br/>
        <b>Budget Tier:</b> {concept['budget_tier']}<br/>
        <b>Release Strategy:</b> {concept['release_type']}<br/>
        <b>Language:</b> {concept['language']}<br/>
        <b>Star Power:</b> {concept['star_power']}/10<br/>
        <b>Novelty Factor:</b> {concept['novelty_factor']}/10<br/>
        <b>Family Appeal:</b> {concept['family_appeal']}/10
        """
        story.append(Paragraph(concept_text, self.styles['Normal']))
        story.append(Spacer(1, 0.5*inch))
        
        # Market Analysis
        story.append(Paragraph("<b>Market Analysis</b>", self.styles['SubTitle']))
        story.append(Spacer(1, 0.2*inch))
        
        market_data = [
            ['Metric', 'Score'],
            ['India Market Fit', f"{prediction['market_scores']['india_fit']}%"],
            ['Global Market Fit', f"{prediction['market_scores']['global_fit']}%"],
            ['Theatrical Potential', f"{prediction['market_scores']['theatrical_potential']}%"],
            ['OTT Potential', f"{prediction['market_scores']['ott_potential']}%"]
        ]
        
        market_table = Table(market_data, colWidths=[3*inch, 2*inch])
        market_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e40af')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 14),
            ('BACKGROUND', (0, 1), (-1, -1), colors.white),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#cbd5e1'))
        ]))
        story.append(market_table)
        story.append(PageBreak())
        
        # Strategic Recommendations
        story.append(Paragraph("<b>Strategic Recommendations</b>", self.styles['SubTitle']))
        story.append(Spacer(1, 0.2*inch))
        
        for idx, rec in enumerate(prediction['recommendations'], 1):
            rec_text = Paragraph(f"{idx}. {rec}", self.styles['Normal'])
            story.append(rec_text)
            story.append(Spacer(1, 0.15*inch))
        
        story.append(Spacer(1, 0.3*inch))
        
        # Target Audience
        story.append(Paragraph("<b>Target Audience</b>", self.styles['SubTitle']))
        story.append(Spacer(1, 0.2*inch))
        
        audience_text = ', '.join(prediction['target_audience'])
        story.append(Paragraph(audience_text, self.styles['Highlight']))
        story.append(Spacer(1, 0.5*inch))
        
        # Similar Successful Movies
        if prediction.get('similar_successful_movies'):
            story.append(Paragraph("<b>Similar Successful Movies</b>", self.styles['SubTitle']))
            story.append(Spacer(1, 0.2*inch))
            
            similar_data = [['Title', 'Genres', 'Score', 'Box Office']]
            for movie in prediction['similar_successful_movies'][:5]:
                similar_data.append([
                    movie['title'],
                    ', '.join(movie['genres']),
                    str(movie['score']),
                    f"₹{movie['box_office']}Cr"
                ])
            
            similar_table = Table(similar_data, colWidths=[2*inch, 2*inch, 1*inch, 1.5*inch])
            similar_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#8b5cf6')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.white),
                ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#cbd5e1'))
            ]))
            story.append(similar_table)
        
        # Build PDF
        doc.build(story)
        buffer.seek(0)
        return buffer
    
    def generate_comparison_report(self, concepts: List[Dict]) -> BytesIO:
        """Generate comparison report for multiple concepts"""
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        story = []
        
        # Title
        title = Paragraph("<b>Concept Comparison Report</b>", self.styles['CustomTitle'])
        story.append(title)
        story.append(Spacer(1, 0.5*inch))
        
        # Comparison table
        table_data = [['Concept', 'Score', 'India Fit', 'Global Fit', 'Label']]
        
        for idx, concept_data in enumerate(concepts, 1):
            concept = concept_data['concept']
            prediction = concept_data['prediction']
            table_data.append([
                f"Concept {idx}\n{', '.join(concept['genres'])}",
                str(prediction['overall_score']),
                str(prediction['market_scores']['india_fit']),
                str(prediction['market_scores']['global_fit']),
                prediction['label']
            ])
        
        comparison_table = Table(table_data, colWidths=[2*inch, 1*inch, 1*inch, 1*inch, 2*inch])
        comparison_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e40af')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.white),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#cbd5e1'))
        ]))
        story.append(comparison_table)
        
        doc.build(story)
        buffer.seek(0)
        return buffer

# Global instance
presentation_generator = StudioPresentationGenerator()